# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://serolfy.github.io/
title: Yair Flores Personal Site
email: yairflowers@gmail.com
author: Yair Flores
description: >  
  Yair Flores Personal Professional Site
copyright: 'Copyright &copy; 2020 Yair Flores. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  #- title: twitter
   # url: https://twitter.com/
  - title: github
    url: https://github.com/serolfy
  - title: linkedin
    url: https://www.linkedin.com/in/yairflores/
